name: Deploy em Produção

on:
  push:
    branches: [main]

jobs:
  deploy-on-BRFD-134:
    runs-on: BRFD

    environment:
      name: Produção

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install Node.js LTS Version
        uses: actions/setup-node@v3
        with:
          node-version: '22.16.0'

      - name: Set up production .env
        run: echo "${{ secrets.PROD_ENV_FILE }}" > .env
        
      - name: Stop Application
        run: |
          pm2 stop BraFurries-Discord || true
          pm2 flush BraFurries-Discord || true
          pm2 delete BraFurries-Discord || true
        shell: bash

      - name: Install PM2
        run: |
          npm install pm2@latest -g --registry=https://registry.npmmirror.com || npm install pm2@latest -g
          pm2 update || true
        shell: bash

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
        shell: bash

      - name: Set Instances
        run: |
          cp i/1 BraFurries-Discord.pm2.json
          rm -Rf i
        shell: bash

      - name: Start Application with PM2
        run: |
          pm2 start BraFurries-Discord.pm2.json
          pm2 save
          pm2 list
        shell: bash
