name: Deploy em Produção

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # ou ubuntu-latest, ou [self-hosted,BRFD] se for runner em prod
    runs-on: BRFD

    environment:
      name: Produção

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Set up Python 3.9.23
        uses: actions/setup-python@v5
        with:
          python-version: 3.9.23

      - name: Set up Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0

      - name: Install PM2 globally
        run: npm install pm2@latest -g
        shell: bash

      - name: Create .env file
        run: printf '%s\n' "${{ secrets.PROD_ENV_FILE }}" > .env
        shell: bash

      - name: Build Python virtualenv & install dependencies
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy with PM2
        shell: bash
        run: |
          pm2 startOrReload BraFurries-Discord.pm2.json --env production
          pm2 save
          pm2 status
