name: Deploy em Produção

on:
  push:
    branches: [main]

jobs:
  deploy-on-BRFD-134:
    runs-on: BRFD

    environment:
      name: Produção

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install Node.js LTS Version
        uses: actions/setup-node@v3
        with:
          node-version: '22.16.0'

      - name: Set up production .env
        env:
          PROD_ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
        run: |
          printf '%s' "$PROD_ENV_FILE" > .env
        
      - name: Stop Application
        run: |
          pm2 stop BraFurries-Discord || true
          pm2 flush BraFurries-Discord || true
          pm2 delete BraFurries-Discord || true
        shell: bash

      - name: Install PM2
        run: |
          npm install pm2@latest -g --registry=https://registry.npmmirror.com || npm install pm2@latest -g
          pm2 update || true
        shell: bash

      - name: Create and activate virtualenv && install Python dependencies
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate
          echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Instances
        run: |
          cp pipeline/1 BraFurries-Discord.pm2.json
          rm -Rf pipeline
        shell: bash

      - name: Start Application with PM2
        run: |
          cd $GITHUB_WORKSPACE
          source .venv/bin/activate
          pm2 start BraFurries-Discord.pm2.json --env production
          pm2 save
          pm2 list
        shell: bash
