cities = {
    "SP":"São Paulo",
    "RJ":"Rio de Janeiro",
    "MG":"Minas Gerais",
    "ES":"Espírito Santo",
    "PR":"Paraná",
    "SC":"Santa Catarina",
    "RS":"Rio Grande do Sul",
    "MS":"Mato Grosso do Sul",
    "MT":"Mato Grosso",
    "GO":"Goiás",
    "DF":"Distrito Federal",
    "AC":"Acre",
    "AM":"Amazonas",
    "RR":"Roraima",
    "RO":"Rondônia",
    "PA":"Pará",
    "AP":"Amapá",
    "TO":"Tocantins",
    "MA":"Maranhão",
    "PI":"Piauí",
    "CE":"Ceará",
    "RN":"Rio Grande do Norte",
    "PB":"Paraíba",
    "PE":"Pernambuco",
    "AL":"Alagoas",
    "SE":"Sergipe",
    "BA":"Bahia",
}