from typing import Literal


cityNames = {
    "SP":"São Paulo",
    "RJ":"Rio de Janeiro",
    "MG":"Minas Gerais",
    "ES":"Espírito Santo",
    "PR":"Paraná",
    "SC":"Santa Catarina",
    "RS":"Rio Grande do Sul",
    "MS":"Mato Grosso do Sul",
    "MT":"Mato Grosso",
    "GO":"Goiás",
    "DF":"Distrito Federal",
    "AC":"Acre",
    "AM":"Amazonas",
    "RR":"Roraima",
    "RO":"Rondônia",
    "PA":"Pará",
    "AP":"Amapá",
    "TO":"Tocantins",
    "MA":"Maranhão",
    "PI":"Piauí",
    "CE":"Ceará",
    "RN":"Rio Grande do Norte",
    "PB":"Paraíba",
    "PE":"Pernambuco",
    "AL":"Alagoas",
    "SE":"Sergipe",
    "BA":"Bahia",
}

cityLetterCodes = {
    "São Paulo":"SP",
    "Rio de Janeiro":"RJ",
    "Minas Gerais":"MG",
    "Espírito Santo":"ES",
    "Paraná":"PR",
    "Santa Catarina":"SC",
    "Rio Grande do Sul":"RS",
    "Mato Grosso do Sul":"MS",
    "Mato Grosso":"MT",
    "Goiás":"GO",
    "Distrito Federal":"DF",
    "Acre":"AC",
    "Amazonas":"AM",
    "Roraima":"RR",
    "Rondônia":"RO",
    "Pará":"PA",
    "Amapá":"AP",
    "Tocantins":"TO",
    "Maranhão":"MA",
    "Piauí":"PI",
    "Ceará":"CE",
    "Rio Grande do Norte":"RN",
    "Paraíba":"PB",
    "Pernambuco":"PE",
    "Alagoas":"AL",
    "Sergipe":"SE",
    "Bahia":"BA",
}

citiesList = Literal[
    "Acre",
    "Alagoas",
    "Amapá",
    "Amazonas",
    "Bahia",
    "Ceará",
    "Distrito Federal",
    "Espírito Santo",
    "Goiás",
    "Maranhão",
    "Mato Grosso",
    "Mato Grosso do Sul",
    "Minas Gerais",
    "Pará",
    "Paraíba",
    "Paraná",
    "Pernambuco",
    "Piauí",
    "Rondônia",
    "Roraima",
    "Rio de Janeiro",
    "Rio Grande do Norte",
    "Rio Grande do Sul",
    "Santa Catarina",
    "São Paulo",
    "Sergipe",
    "Tocantins",
]